### ISSUE TITLE
叙白大佬deepx请教个问题

### ISSUE THREAD

**Issue by bingbaicai** [xubai-owo/xubai-owo.github.io#7]
你离开了q群只能在这里麻烦你了
我部署了deepx的docker了
我要怎么使用啊
你脚本里面说的authkey我不知道怎么弄
我是部署的这个https://github.com/OwO-Network/DeepLX

**Comment by xubai-owo** [comment]
我没有部署过，我也不清楚，而且不要直接发issue, 可以在我别的issues下边发评论

**Comment by bingbaicai** [comment]
> 我没有部署过，我也不清楚，而且不要直接发issue, 可以在我别的issues下边发评论

哈哈
作者说多找自己的问题😂
